export const PARTNERS = [
    {
        firstname: "Abderrezague",
        surname: "Ismail",
        storename: "Ph Abdou",
        email: "test@ismail.com",
        wilaya: "Mascara",
        city: "Sig",
        adress: "Rue 1er Novembre",
        speciality: "Pharmacie",
        start_date: "2021-01-01",
        phone_one: 123456,
        phone_two: 123456,
        language: "Arabic",
        status: true,
    },
    {
        firstname: "Mohamed",
        surname: "Taha",
        storename: "Ph Taha",
        email: "taha@test.com",
        wilaya: "sidi bel abbes",
        city: "mohammadia",
        adress: "Rue 1er Novembre",
        speciality: "Pharmacie",
        start_date: "2021-01-01",
        phone_one: 123456,
        phone_two: 123456,
        language: "Arabic",
        status: true,
    },
]